### ISSUE TITLE
OSX copy (command+C) doesn't seem to work

### ISSUE THREAD

**Issue by shenning00** [belltown/violetbug#1]
I am trying to copy and past from violetbug and I use OSX key commands alot. 

The key command (command+C) does not seem to work.

The right-click context menu has an option for copy that does work.

Great tool! Thanks.

**Comment by belltown** [comment]
I hope to have a fix for that shortly. I believe that macOS requires the cut/copy/paste shortcuts to be implemented in the Application Menu, rather than in the context (right-click) menu. I plan to add an Edit menu to the Application Menu that will hopefully take care of the problem.

**Comment by belltown** [comment]
I have a quick question for you, @shenning00: Do the keyboard shortcuts for Clear Line (Esc) and Clear Screen (Alt-C) work on your Mac in a connection screen, or just the context menu selections?

**Comment by shenning00** [comment]
Seems like the Clear Screen(Alt-C) is working.

I don't think the Clear Line (Esc) is working. I tried Esc and the context menu. This didn't seem to work from either. But, I've never used that so not exactly sure what is supposed to do.

**Comment by belltown** [comment]
If you're typing debug commands in the input text box at the bottom of the screen, then press Esc (or right-click>Clear Line), then it should clear the input text line. Since the Alt-C (Clear Screen) works, I'd assume that Esc (Clear Line) would work as well, unless the Mac does something funky with the Esc key.

**Comment by shenning00** [comment]
Oh, yep that works as well.

**Comment by belltown** [comment]
Thanks. I was hoping for that. It must just be the cut/copy/paste shortcuts that need to be in the Application Menu. I'll get to work on that tomorrow.

**Comment by belltown** [comment]
Cut/copy/paste should now be working on macOS in release v0.0.2.

**Comment by shenning00** [comment]
I'll give it a try. Thanks.

**Comment by shenning00** [comment]
Yep - (Command-C) copy works now. Thanks.

**Comment by belltown** [comment]
Great! I'll close this issue then.
