### ISSUE TITLE
Is there a way to filter the console?

### ISSUE THREAD

**Issue by marcochin** [belltown/violetbug#2]
Is there a way to filter the debug log messages by a certain word?
Its hard to debug something when your screen is flooded with massive amounts of text.

For instance (normal debug log):
Msg A
Msg B
Msg C
Msg A

Filtering for Msg A (debug log w/ filter):
Msg A
Msg A

**Comment by marcochin** [comment]
Would it be hard or possible in the future to implement?

**Comment by belltown** [comment]
I suppose it would be possible. I'll add it to my list of possible future enhancements, although I'm currently not doing any more work on VioletBug, so I can't say if, or when, this will ever get implemented.

**Comment by marcochin** [comment]
I'm sure roku dev community would love you for it if you can! Will make debugging so much easier! Anyways Thanks.
